
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  #Github: https://github.com/yours
  #Codepen: https://codepen.io/yours
  #Dribbble: https://dribbble.com/yours
  #Twitter: https://twitter.com/yours
  #知乎: https://www.zhihu.com/people/yours
  #掘金: https://juejin.im/user/yours
  AO3: https://archiveofourown.org/users/LemonHyphae/pseuds/LemonHyphae
  Discord: https://discord.gg/5uRdsDfqjD
  Steam: https://steamcommunity.com/profiles/76561198262536057/
  Email: mailto:moonreversenight@outlook.com
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: xx-xxxxxxx-xx

# comment module
comment:
  enable: true
  type: utterances # valine | utterances

  # valine 需要的参数
  appId: your-app-id
  appKey: your-app-key
  placeholder: say something
  notify: false
  verify: false
  avatar: mp

  # utterances (https://utteranc.es/) 需要的参数
  repo: Ochann/Comments
  issue_term: pathname
  theme: github-light


# search
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 5
  unescape: false
  preload: false
